### ISSUE TITLE
Add ASN to mtr output

### ISSUE THREAD

**Issue by jviersel** [NLNOG/ring-sqa#11]
mtr (at least at my Linux machines) has the --aslookup or -z option to add the AS-number of the ipaddress to the output. Adding the ASN to the output would save some time on debugging.

**Comment by job** [comment]
This is (undocumented) already solved through this commit: https://github.com/NLNOG/ring-sqa/pull/9

on your RING node you can configure `mtr.args` in the config to make it do lookups.

The big downside is, that `mtr` will communicate with `whois.radb.net` during the traceroute to resolve the IPs to ASNs (this is done based on inverse lookups on IRR data), this can be blocking duren the traceroute if for instance the ring node cannot reach `whois.altdb.net` because of the very outage it has detected which triggered the alert.

I recommend against using it to ensure the traceroutes are collected ASAP. You can always throw the traceroute through a post processing script to enrich it with meta-data such as ASN, or GeoIP stuff.
